### ISSUE TITLE
Content Suggestions

### ISSUE THREAD

**Issue by connollybrenna** [TerribleDev/nashua#1]
Sports Centers
- Historic Holman Stadium
- Conway Arena
- Nashua Sports Academy

Playgrounds and parks
- Mine falls
- Roby
- Greeley
- School playgrounds
- Sculptures

Breweries

Events
- ComicFest
- Summer Concert Series
- Holiday Stroll
- Taste of Downtown Nashua

Walking/Biking Tours

Theater and Arts
- Peacock Players
- ActorSingers
- Nashua Theater Guild
- Riverwalk music

Nashua Geography

**Comment by TerribleDev** [comment]
I'm going to break these down into new issues, and create a milestone to work on them. Thanks for pulling them into github in a concise way.
